config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :dashboard, only: [:show] do
    resources :vinyls, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :vinyls, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :vinyls
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :vinyls
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vinyls, dependent: :destroy
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  belongs_to :genre
  belongs_to :artist
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # before_action :set_genre, only: [:new, :create]
  # before_action :set_author, only: [:new, :create]
  before_action :authenticate_user!

  def show
    @vinyls = Vinyl.where(user: current_user).all
    @vinyl = Vinyl.new
  end

  def new
    @vinyl = Vinyl.new
  end

  def create
    @vinyl = Vinyl.new(vinyl_params)
    @vinyl.user = current_user # Associer le vinyl à l'utilisateur actuel
    if @vinyl.save
      redirect_to dashboard_path, notice: "Vinyl successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @vinyl = Vinyl.find(params[:id])
    if @vinyl.update(vinyl_params)
      redirect_to vinyl_path(@vinyl)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @vinyl = Vinyl.find(params[:id])
    @vinyl.destroy
    redirect_to dashboard_path, notice: "Vinyl successfully destroyed."
  end


  private

  def vinyl_params
    params.require(:vinyl).permit(:name, :price, :year, :condition, :time, :genre_id, :artist_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @vinyls = Vinyl.all
  end

end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  def show
    @vinyl = Vinyl.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<h1> dashboard de l'utilisateur</h1>


<h2>Liste des vinyls de <%= current_user.email %> </h2>
  <ul>
    <% @vinyls.each do |vinyl| %>
      <li>
        <%= link_to vinyl.name, vinyl_path(vinyl)%>
      </li>
    <% end %>
</ul>

<%= simple_form_for @vinyl, url: vinyls_path, method: :post do |f| %>
  <%= f.input :name %>
  <%= f.input :year %>
  <%= f.input :condition %>
  <%= f.input :time %>
  <%= f.association :genre, collection: Genre.all, prompt: "Select a genre" %>
  <%= f.association :artist, collection: Artist.all, prompt: "Select an artist" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VinyleGlory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h2>Lste des vinyls du magasin</h2>
  <ul>
    <% @vinyls.each do |vinyl| %>
      <li>
        <%= link_to vinyl.name, vinyl_path(vinyl)%>
      </li>
    <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/stef1380", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path(current_user), class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vinyls/show.html.erb
<h1> voici le vinyl: </h1>

 <%= @vinyl.name %>